### ISSUE TITLE
No conversion from `rcl_interfaces/msg/Log` and `rosgraph_msgs/Log`

### ISSUE THREAD

**Issue by Timple** [contradict/ros-humble-ros1-bridge#2]
When running the bridge I get this error:

```
ros1-bridge_1  | failed to create 2to1 bridge for topic '/rosout' with ROS 2 type 'rcl_interfaces/msg/Log' and ROS 1 type 'rosgraph_msgs/Log': No template specialization for the pair
```

Can easily be verified with this docker-compose file:
```yaml
version: "2.1"
services:
  roscore:
    image: "ros:noetic"
    network_mode: host
    command: roscore
  ros1-bridge:
    image: bridge
    network_mode: host
    command: ros2 run ros1_bridge dynamic_bridge
```

However during compilation I can see that `rcl_interfaces` and `rosgraph` are found. Do you suffer from the same?
